trigger:
  - "*"

pool:
  vmImage: ubuntu-latest
  name: "test pipelines"

variables:
  buildConfiguration: "Release"
  wwwrootDir: "Tailspin.SpaceGame.Web/wwwroot"
  dotnetSdkVersion: "6.x"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET SDK $(dotnetSdkVersion)"
    inputs:
      version: "$(dotnetSdkVersion)"

  - task: Npm@1
    displayName: "Run npm install"
    inputs:
      verbose: false

  - script: "npm install gulp-cli"
    displayName: "Install Gulp CLI locally"

  - script: "./node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)"
    displayName: "Compile Sass assets"

  - script: "./node_modules/.bin/gulp"
    displayName: "Run gulp tasks"

  - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: "Write build info"
    workingDirectory: $(wwwrootDir)

  - task: DotNetCoreCLI@2
    displayName: "Restore project dependencies"
    inputs:
      command: "restore"
      projects: "**/*.csproj"

  - template: templates/build.yml
    parameters:
      buildConfiguration: "Debug"

  - template: templates/build.yml
    parameters:
      buildConfiguration: "Release"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    condition: succeeded()
